### PR TITLE
Mrc32 better multichain approach for mor token

### PR DESCRIPTION
**Pull request by KelvinThai**
This PR propose a better multichain approach for the MOR token

### CODE REVIEW

**Comment by antonbosss** [comment]
Hi a few points I think important to share:
- MOR has LayerZero OFT [integrated](https://github.com/MorpheusAIs/SmartContracts/blob/main/contracts/MOROFT.sol) and currently under security audit
- I think that the correct MRC number is 32 and 31 is existed.
- seems like MRC is missing some points according to the [MRC Request template](https://github.com/MorpheusAIs/MRC/blob/main/MRC00.md)

**Comment by DavidAJohnston** [comment]
Interesting suggestions to make Morpheus Multi-chain / messaging agnostic. Needs a lot more detail on HOW to do that.
Also as @antonbosss noted above MRC31 is taken, please update this to MRC32 and I'll merge this for discussion. @KelvinThai

**Comment by KelvinThai** [comment]
Thank you guys for the clarification, I renamed it to 30. 
For the execution plan, we may need a more detail document. If you want to add it the proposal, happy to do it as well.

**Review by DavidAJohnston — APPROVED** [review]
Thanks. Merging for Discussion.

**Pull request merged**
